SUPABASE_URL = "https://abdccnrulkolfqwemxan.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZGNjbnJ1bGtvbGZxd2VteGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzg1NjYsImV4cCI6MjA3NDkxNDU2Nn0.I8ifTNuXxv-GNRlPpkyyHWAkJQrGLwLczFo9yZGTpCg"
